sraoss/pg_ivm

- README.md
Incremnetal -> Incremental
Installaion -> Installation
The same typo also exists on GitHub repository description. It can be fixed by repo owners/admins using the Web interface.
> Fix simple typos in README

- pg_ivm--1.0.sql
This currently crashes the server: `SELECT create_immv(NULL, 'SELECT * FROM test');` . 
Marking the function STRICT will avoid calling it with NULL arguments. (not sure if you have a SQL upgrade script policy yet)
Alternative would be check for NULL in create_immv.
> Make create_immv STRICT

- expected/pg_ivm.out
- sql/pg_ivm.sql
As of PG15, PUBLIC CREATE was revoked from public schema, so
we have to grant it in contrib_regression database.
Issue #11
> Fix the test to grant create permissions on the public schema

- Makefile
- createas.c
- expected/create_immv.out
- expected/refresh_immv.out
- matview.c
- pg_ivm--1.0.sql
- pg_ivm.c
- pg_ivm.h
- sql/create_immv.sql
- sql/refresh_immv.sql
This patch add refresh command(without document).
refresh_immv(immv_name, with_no_data) has two argument. immv_name
is incrementaly matview name, and with_no_data is refresh command
option.
its with_no_data and WITH NO DATA option of REFRESH MATERIAEZED VIEW
mean the same. However, with_no_data has no data, but can be
referenced by SELECT.
e.g.
```
test=# CREATE TABLE test(id int);
CREATE TABLE
test=# INSERT INTO test SELECT generate_series(1, 5);
INSERT 0 5
test=# SELECT create_immv('immv', 'SELECT * FROM test');
NOTICE:  could not create an index on immv "immv" automatically
DETAIL:  This target list does not have all the primary key columns, or this view does not contain DISTINCT clause.
HINT:  Create an index on the immv for efficient incremental maintenance.
create_immv …
```
> Add refresh_immv() function

- Makefile
- createas.c
- expected/pg_ivm.out
- matview.c
- pg_ivm.c
- pg_ivm.h
- ruleutils.c
- ruleutils_13.c
- ruleutils_14.c
- sql/pg_ivm.sql
In order to re-calculate min/max values for groups where the min
or max value is deleted, we need the view query definition in string
form. However, pg_get_viewdef cannot be used for this purpose because
IMMV's defenition is in pg_ivm_immv but not pg_rewrite.  Therefore,
we have to convert query definition in pg_ivm_immv to query
definition string. We can use pg_get_querydef in PG15, but we cannot
in PG14 or earlier, so we use codes in ruleutil.c copied from PG13
or PG14 depending versions.
> Support min/max aggregates

- matview.c
I got a compiler warning on gcc 9.4.0:
```
matview.c: In function ‘ExecRefreshImmv’:                                                
matview.c:449:3: warning: ‘dataQuery’ may be used uninitialized in this function [-Wmaybe-uninitialized]
449 |   CreateIvmTriggersOnBaseTables(dataQuery, matviewOid, false);                   
|   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
```
Not a bug, just compiler not understanding that dataQuery is always initialized if !skipData.
> Fix gcc warning in ExecRefreshImmv

- createas.c
- expected/pg_ivm.out
We usually try to create a unique index on an IMMV for both performance and constraint reasons. However, we don't need such index for an aggregate view without GROUP BY because it has always only one row. Also, we don't need to raise NOTICE message to suggest to create an index.
This change was mistakenly introduced in cfe9491e6b2168, but it should have been a separate commit. In this commit, a typo and tests are fixed.
> Fix comment typo and test for aggregates without GROUP BY

- expected/pg_ivm.out
- matview.c
- pg_ivm.h
- ruleutils.c
- sql/pg_ivm.sql
Previously, a query string returned from pg_ivm_get_querydef
did not include column names specified when IMMV was defined
by create_immv. This caused failures in maintenance of MIN/MAX
aggregate views whose columns had alias names.
It is fixed by rewriting the result column name in the parse tree
using the view's tuple descriptor prior to calling pg_get_querydef
for PG15 or higher, or specifying the tuple descriptor to
get_query_def for PG14 or earlier.
> Fix to get view definition string with correct column names

- expected/pg_ivm.out
- matview.c
- pg_ivm--1.2--1.3.sql
- pg_ivm.h
- sql/pg_ivm.sql
When multiple tables are updated or the view contains a self-join, we need to calculate table states that was before it is modified during incremental view maintenance. For get the pre-update state, tuples inserted in a command must be removed when the table is scanned.
Previously, we used xmin and cmin system columns for this purpose, but this way is problematic because after a tuple is frozen, its xmin no longer has any meaning. Actually, we will get inconsistent view results after XID wraparound.
Also, we can see similar similar inconsistency when using sub-transaction because xmin values do not always monotonically increasing by command executions.
To fix this, we use a snapshot that taken just before the table is modified for checking tuple visibility in pre-state table instead of …
> Use snapshot to check tuple visibility in pre-update state

- createas.c
- expected/create_immv.out
- pg_ivm.c
- pg_ivm.h
- sql/create_immv.sql
Previously, IMMV including IMMV in its definition was created by create_immv(), but it is not supported by IMMV. This patch now raises an error on create_immv().
> Fix not to create IMMV icluding other IMMV(#30)

- createas.c
- expected/pg_ivm.out
- sql/pg_ivm.sql
It is intended that a unique index is created only if all primary keys of tables in FROM clause appear in the target list. For this purpose, pull_varnos_of_level was used to extract relations in the FROM clause, but it is incorrect and actually we should use get_relids_in_jointree.
Due to this bug, an index could be created even even where there is a pkey attribute from just one of relations in FROM clause.
> Fix a bug of automatic index creation

- createas.c
- expected/pg_ivm.out
- sql/pg_ivm.sql
Previously, when a subquery is used a unique index could not be created even if all primary key attributes appear in the target list.
> Fix automatic index creation to support subqueries

- matview.c
Previously, it caused an error due to an ambiguous reference at the maintenance time because generate_series is used internally. This is fixed by using an alias name for the internal genearet_series.
> Fix to allow generate_sereis in FROM clause

- createas.c
- expected/pg_ivm.out
- sql/pg_ivm.sql
Some conditions on view definition that should be prohibited, for example,
- SELECT ... FROM func(..., (SELECT ... FROM ...), ..) ...;
- SELECT expr(SELECT ... FROM ...) FROM ...;
were not checked. Also, some error messages and the order of tests are improved.
> Fix regression tests on subqueries

- Makefile
- README.md
- createas.c
- expected/pg_ivm.out
- matview.c
- pg_ivm.h
- sql/pg_ivm.sql
- subselect.c
Simple CTEs which does not contain aggregates or DISTINCT are now supported similarly to simple sub-queries.
Before a view is maintained, all CTEs are converted to corresponding subqueries to enable to treat CTEs as same as subqueries. For this end, codes of the static fnction inline_cte in the core (optimizer/plan/subselect.c) was imported.
> Add CTE support

- README.md
- createas.c
- expected/pg_ivm.out
- matview.c
- pg_ivm.h
- sql/pg_ivm.sql
Simple EXISTS clause is supported by this patch. A query is not supported when WHERE clause has OR-condition or JOIN-condition is not contained by targetlist.
> Support exists_subquery

- README.md
- createas.c
- matview.c
- pg_ivm.c
- pg_ivm.h
Build errors/warnings against PostgreSQL 16 are fixed. Also, adapted to the change of codes, including:
- Get rid of the "new" and "old" entries in a view's rangetable. (Althogh, removed codes were dead codes because pg_ivm doesn't
have any rules in pg_rewrite.)
- Rework query relation permission checking
- Require empty Bitmapsets to be represented as NULL
> Add support for PostgreSQL 16 (#69)

- README.md
This trivial Pull Request fixes a typo in the heading of the documentation describing the `create_immv()` function.
> Fix typo in README heading

- pg_ivm.c
#77 Fix the problem that preloaded pg_ivm will break Postgresql's regression tests.
I don't know exactly why PgIvmImmvRelationId() will return an invalidOid, but checking if it is will help fix this problem.
> Check if PgIvmImmvRelationId is invalid before open it

- matview.c
Hi
I have noticed that this extension does not compile with PG17 after https://github.com/postgres/postgres/commit/d3a38318ac614f20a9e2e163bba083d15be54f06
so i decided to provide little help for your future rebase work
> Fix compile with PG17

- README.md
- createas.c
- matview.c
- pg_ivm.h
Compilation errors and warning are fixed.
The design of create_immv is also chaned as similar to PG17, that is, firstly a relation is created without data then it is populated by using the refresh logic.
This commit contains the following changes:
- Change functions to use a safe search_path during maintenance operations when used with PostgreSQL 17
This prevents maintenance operations (automatic maintenance of IMMVs and
refresh_immv) from performing unsafe access.  Functions used by IMMVs that
need to reference non-default schemas must specify a search path during
function creation.
- refresh_immv can be executed by users with the MAINTAIN privilege when used with PostgreSQL 17
Issue #90
> Add support for PostgreSQL 17

- createas.c
- pg_ivm.c
- pg_ivm.h
Hi! while adapting this extension for Greenplum I happened to notice that ExecCreateImmv func accept params that does not have any use. 
SO I propose a small refactoring. This reduce maintenance pain for Greenplum.
> Drop unused params from ExecCreateImmv function

- pg_ivm.c
1. Saves from race condition while doing table scan in object acess hook, which arises when the current drop object is pg_ivm_immv's toast table, which looks up for primary key which already got dropped earlier.
2. Use RangeVarGetRelidExtended(... AccessShareLock ...) instead of get_relname_relid().  That way, DROP EXTENSION can't cause errors in concurrent sessions that are in the middle of running the hook.
Tested in GCE VM with postgres 15
* Drop extension failure in pg_ivm - 
* Drop extension working after fix -
> Drop extension failure.

- createas.c
- expected/pg_ivm.out
- sql/pg_ivm.sql
Previously, a unique index is automatically created even when a set-returning function is contained in FROM clause, but this results in an error due to key duplication. Now, an index is not created automatically when a relation other than table, sub-query, or join is contained in FROM clause.
Issue (#99)
> Prevent automatic index creation with set-returning function

- Makefile
- README.md
- createas.c
- expected/create_immv.out
- expected/pg_ivm.out
- expected/refresh_immv.out
- matview.c
- pg_ivm--1.0.sql
- pg_ivm--1.10.sql
- pg_ivm--1.9--1.10.sql
- pg_ivm.c
- pg_ivm.h
- sql/create_immv.sql
- sql/pg_ivm.sql
- sql/refresh_immv.sql
Previously, pg_upgrade failed due to the permission denied because the pg_ivm_immv catalog was in the pg_catalog catalog (Issue #79). To fix this, all objects created by pg_ivm are moved to theschema pgivm, which is also created by pg_ivm.
pg_ivm is still not relocatable and this must be installed to the pgivm schema because the catalog and some internal functions are referred to unqualified by the schema name from the pg_ivm module. In future, this might be able to relocatable during installation, though.
This commit affects compatibility with previous releases. To allow to access objects like create_immv function as previous, you need to qualify them with the schema name or setup search_path properly.
> Change the schema from pg_catalog to pgivm

- expected/pg_ivm.out
- matview.c
- sql/pg_ivm.sql
A RTE of modified table in the view definition query is substituted by a subquery representing a delta table or a pre-update state table during view maintenance. After this rewrite, Var that used to reference the table column should become to references the corresponding column in the subquery targetlist. Previously, the targetlist contained only existing columns of the table. This was not a problem as long as the table didn't have any dropped column because varattnos in the query tree  was identical to resno of the targetlist. However, if the table has a dropped column, we cannot assume this correspondence, so an error like the following occurred in that situation.
ERROR: could not find attribute 43 in subquery targetlist
To fix it,  put "null" as a dummy value at the position in the …
> Fix targetlist of subquery substituting modified table

- pg_ivm.h
Fix build errors on Windows by adding PGDLLEXPORT to some function declarations in pg_ivm.h.
This PR adds the PGDLLEXPORT macro to the declarations of several functions (IVM_immediate_before, IVM_immediate_maintenance, ivm_visible_in_prestate) in pg_ivm.h.  
This resolves linkage errors that occurred when building pg_ivm on Windows with PostgreSQL 17.4 and Meson, due to mismatches between the function declarations and their definitions.
- ISSUE #138
> Fix Windows linkage errors by adding PGDLLEXPORT to function declarations

- createas.c
Ensure that newly added column information is passed to heap_form_tuple(). Previously, omission of this data led to a segmentation fault when building with MSVC, though the issue has not not observed on Linux.
> Fix potential segmentation fault in create_immv

- expected/pg_ivm.out
- sql/pg_ivm.sql
Building PostgreSQL with -DENFORCE_REGRESSION_TEST_NAME_RESTRICTIONS causes the regression tests of pg_ivm to fail, because the role names used in the tests are not compliant with what upstream expects.
Enforcing restrictions in the regression tests is a good practice to have, as roles are shared objects and running the tests could manipulate existing clusters in unwanted ways.
> Prefix role names in regression tests with "regress_"
